# UNDO-HITLIST.ps1 - Generated 08/19/2025 14:11:27
Write-Host 'Restoring 85 files...' -ForegroundColor YellowMove-Item 'D:\Dev\kha\_archive\2024\diagnostic\find_all_o2_files.py' 'D:\Dev\kha\find_all_o2_files.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\find_all_stubs.py' 'D:\Dev\kha\find_all_stubs.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\find_brace_issue.py' 'D:\Dev\kha\find_brace_issue.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\find_duplicate_brace.py' 'D:\Dev\kha\find_duplicate_brace.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\find_duplicate_exports.py' 'D:\Dev\kha\find_duplicate_exports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\find_duplicate_section.py' 'D:\Dev\kha\find_duplicate_section.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\find_field_mismatches.py' 'D:\Dev\kha\find_field_mismatches.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\find_google_drive.ps1' 'D:\Dev\kha\find_google_drive.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\find_intent_usage.ps1' 'D:\Dev\kha\find_intent_usage.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\find_line_595.py' 'D:\Dev\kha\find_line_595.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\find_syntax_error.py' 'D:\Dev\kha\find_syntax_error.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\find_textureload_issues.ps1' 'D:\Dev\kha\find_textureload_issues.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\find_yesterday_files.py' 'D:\Dev\kha\find_yesterday_files.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\CRITICAL_FIX_NOW.ps1' 'D:\Dev\kha\CRITICAL_FIX_NOW.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\complete_fix_all.py' 'D:\Dev\kha\complete_fix_all.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\final_check.py' 'D:\Dev\kha\final_check.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\final_complete_fix.py' 'D:\Dev\kha\final_complete_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\final_concept_fix.py' 'D:\Dev\kha\final_concept_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\final_fix.py' 'D:\Dev\kha\final_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\final_fixes.py' 'D:\Dev\kha\final_fixes.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\FINAL_MERGE_GATE.bat' 'D:\Dev\kha\FINAL_MERGE_GATE.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\final_packaging_fix.cjs' 'D:\Dev\kha\final_packaging_fix.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\final_push_fix.ps1' 'D:\Dev\kha\final_push_fix.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\final_sanity_check.bat' 'D:\Dev\kha\final_sanity_check.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\final_shader_check.ps1' 'D:\Dev\kha\final_shader_check.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\final_shader_validation.ps1' 'D:\Dev\kha\final_shader_validation.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\final_sync.ps1' 'D:\Dev\kha\final_sync.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\final_system_check.py' 'D:\Dev\kha\final_system_check.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\final_scripts\final_test.ps1' 'D:\Dev\kha\final_test.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\old_scripts\APPLY_TRACE_FIXES.bat' 'D:\Dev\kha\APPLY_TRACE_FIXES.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\old_scripts\claude_optimization_clean.ps1' 'D:\Dev\kha\claude_optimization_clean.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\old_scripts\claude_optimization_integrated.ps1' 'D:\Dev\kha\claude_optimization_integrated.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\old_scripts\claude_optimization_protocol.ps1' 'D:\Dev\kha\claude_optimization_protocol.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\old_scripts\claude_optimization_test.ps1' 'D:\Dev\kha\claude_optimization_test.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\old_scripts\continue_fix.bat' 'D:\Dev\kha\continue_fix.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\check_concept_counts.bat' 'D:\Dev\kha\check_concept_counts.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\check_concept_mesh_rename.bat' 'D:\Dev\kha\check_concept_mesh_rename.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\validate_audit.py' 'D:\Dev\kha\validate_audit.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\validate_blending.py' 'D:\Dev\kha\validate_blending.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\validate_entropy_integration.py' 'D:\Dev\kha\validate_entropy_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\validate_system.py' 'D:\Dev\kha\validate_system.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_all_fixes.py' 'D:\Dev\kha\verify_all_fixes.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_bdg_integration.py' 'D:\Dev\kha\verify_bdg_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_beyond_integration.py' 'D:\Dev\kha\verify_beyond_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_bps_config.py' 'D:\Dev\kha\verify_bps_config.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_bulletproof_av_fixes.py' 'D:\Dev\kha\verify_bulletproof_av_fixes.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_canonical_concept_mesh.py' 'D:\Dev\kha\verify_canonical_concept_mesh.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_canonical_launcher.py' 'D:\Dev\kha\verify_canonical_launcher.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_dickbox_hologram_system.py' 'D:\Dev\kha\verify_dickbox_hologram_system.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_entropy.py' 'D:\Dev\kha\verify_entropy.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_exports.py' 'D:\Dev\kha\verify_exports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_extraction_quality.py' 'D:\Dev\kha\verify_extraction_quality.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_extraction_quality_fixed.py' 'D:\Dev\kha\verify_extraction_quality_fixed.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_final_state.py' 'D:\Dev\kha\verify_final_state.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_fixes.py' 'D:\Dev\kha\verify_fixes.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_injection_import.py' 'D:\Dev\kha\verify_injection_import.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_mcp_fix.py' 'D:\Dev\kha\verify_mcp_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_mcp_setup.py' 'D:\Dev\kha\verify_mcp_setup.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_mesh_separation.py' 'D:\Dev\kha\verify_mesh_separation.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_numpy_abi.py' 'D:\Dev\kha\verify_numpy_abi.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_penrose.py' 'D:\Dev\kha\verify_penrose.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\VERIFY_PENROSE_COMPLETE.bat' 'D:\Dev\kha\VERIFY_PENROSE_COMPLETE.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_penrose_import_chain.py' 'D:\Dev\kha\verify_penrose_import_chain.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_penrose_integration.py' 'D:\Dev\kha\verify_penrose_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\VERIFY_PENROSE_SIMPLE.bat' 'D:\Dev\kha\VERIFY_PENROSE_SIMPLE.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_phase2.bat' 'D:\Dev\kha\verify_phase2.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_phase2_scholarsphere.py' 'D:\Dev\kha\verify_phase2_scholarsphere.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_phase3_memory.py' 'D:\Dev\kha\verify_phase3_memory.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_phase4_persona.py' 'D:\Dev\kha\verify_phase4_persona.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_phase5_runtime.py' 'D:\Dev\kha\verify_phase5_runtime.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_prosody_endpoints.py' 'D:\Dev\kha\verify_prosody_endpoints.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_prosody_features.py' 'D:\Dev\kha\verify_prosody_features.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_rank14.py' 'D:\Dev\kha\verify_rank14.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_rank8_stability.py' 'D:\Dev\kha\verify_rank8_stability.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_real_mcp.py' 'D:\Dev\kha\verify_real_mcp.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_refactor.py' 'D:\Dev\kha\verify_refactor.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_setup.py' 'D:\Dev\kha\verify_setup.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_soliton_fixes.py' 'D:\Dev\kha\verify_soliton_fixes.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_syntax_fix.py' 'D:\Dev\kha\verify_syntax_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_system.py' 'D:\Dev\kha\verify_system.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_tori_fixes.py' 'D:\Dev\kha\verify_tori_fixes.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_tori_fixes_v2.py' 'D:\Dev\kha\verify_tori_fixes_v2.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_tori_fixes_v3.py' 'D:\Dev\kha\verify_tori_fixes_v3.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_tori_ready.py' 'D:\Dev\kha\verify_tori_ready.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\validation\verify_torus_cells_working.py' 'D:\Dev\kha\verify_torus_cells_working.py' -Force
Write-Host 'Restored 85 files!' -ForegroundColor Green
