# UNDO-TARGETED.ps1 - Generated 08/19/2025 13:55:43
# Restores files to original locations

Write-Host 'Restoring 562 files to root...' -ForegroundColor Yellow
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\benchmark_embedding_speed.py' 'D:\Dev\kha\benchmark_embedding_speed.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\benchmark_penrose_5200.py' 'D:\Dev\kha\benchmark_penrose_5200.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\benchmark_penrose_direct.py' 'D:\Dev\kha\benchmark_penrose_direct.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\benchmark_penrose_holography.py' 'D:\Dev\kha\benchmark_penrose_holography.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\benchmark_penrose_only.py' 'D:\Dev\kha\benchmark_penrose_only.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\benchmark_penrose_simple.py' 'D:\Dev\kha\benchmark_penrose_simple.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\cache_aware_omega_test.py' 'D:\Dev\kha\cache_aware_omega_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\godmode_stress_test.py' 'D:\Dev\kha\godmode_stress_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\minimal_test.py' 'D:\Dev\kha\minimal_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\quick_omega_test.py' 'D:\Dev\kha\quick_omega_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\quick_pdf_test.py' 'D:\Dev\kha\quick_pdf_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\quick_soliton_test.py' 'D:\Dev\kha\quick_soliton_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\quick_speed_test.py' 'D:\Dev\kha\quick_speed_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\quick_test.py' 'D:\Dev\kha\quick_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\robust_omega_test.py' 'D:\Dev\kha\robust_omega_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\serve_embeddings_minimal_test.py' 'D:\Dev\kha\serve_embeddings_minimal_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\serve_embeddings_test.py' 'D:\Dev\kha\serve_embeddings_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\smoke_test.py' 'D:\Dev\kha\smoke_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\supercharged_legendary_test.py' 'D:\Dev\kha\supercharged_legendary_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_100_percent_bulletproof.py' 'D:\Dev\kha\test_100_percent_bulletproof.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_500_diagnostic.py' 'D:\Dev\kha\test_500_diagnostic.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_advanced.py' 'D:\Dev\kha\test_advanced.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_albert.py' 'D:\Dev\kha\test_albert.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_albert_geodesics.py' 'D:\Dev\kha\test_albert_geodesics.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_albert_mesh_connection.py' 'D:\Dev\kha\test_albert_mesh_connection.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_api_connectivity.py' 'D:\Dev\kha\test_api_connectivity.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_api_integration.py' 'D:\Dev\kha\test_api_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_api_port_config.py' 'D:\Dev\kha\test_api_port_config.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_api_startup.py' 'D:\Dev\kha\test_api_startup.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_ascii_safe_mcp.py' 'D:\Dev\kha\test_ascii_safe_mcp.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_atomic_nonetype_fix.py' 'D:\Dev\kha\test_atomic_nonetype_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_auth_python.py' 'D:\Dev\kha\test_auth_python.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_backend_endpoints.py' 'D:\Dev\kha\test_backend_endpoints.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_basic.py' 'D:\Dev\kha\test_basic.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_basic_flow.py' 'D:\Dev\kha\test_basic_flow.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_batch_performance.py' 'D:\Dev\kha\test_batch_performance.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_beyond_integration.py' 'D:\Dev\kha\test_beyond_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_bps_imports.py' 'D:\Dev\kha\test_bps_imports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_bps_imports_v2.py' 'D:\Dev\kha\test_bps_imports_v2.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_bps_standalone.py' 'D:\Dev\kha\test_bps_standalone.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_bulletproof_final.py' 'D:\Dev\kha\test_bulletproof_final.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_bulletproof_mcp.py' 'D:\Dev\kha\test_bulletproof_mcp.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_bulletproof_serialization.py' 'D:\Dev\kha\test_bulletproof_serialization.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_chat_api.py' 'D:\Dev\kha\test_chat_api.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_collective_consciousness.py' 'D:\Dev\kha\test_collective_consciousness.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_compile.py' 'D:\Dev\kha\test_compile.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_components.py' 'D:\Dev\kha\test_components.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_conceptmesh_fix.py' 'D:\Dev\kha\test_conceptmesh_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_conceptmesh_import.py' 'D:\Dev\kha\test_conceptmesh_import.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_concept_extraction.py' 'D:\Dev\kha\test_concept_extraction.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_concept_injection.py' 'D:\Dev\kha\test_concept_injection.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_concept_mesh_3_fixed.py' 'D:\Dev\kha\test_concept_mesh_3_fixed.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_concept_mesh_e2e.py' 'D:\Dev\kha\test_concept_mesh_e2e.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_concept_mesh_e2e_old.py' 'D:\Dev\kha\test_concept_mesh_e2e_old.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_concept_mesh_entity_linking.py' 'D:\Dev\kha\test_concept_mesh_entity_linking.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_concept_mesh_import.py' 'D:\Dev\kha\test_concept_mesh_import.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_concept_storage.py' 'D:\Dev\kha\test_concept_storage.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_config.py' 'D:\Dev\kha\test_config.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_debug_ingestion.py' 'D:\Dev\kha\test_debug_ingestion.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_diff_route_import.py' 'D:\Dev\kha\test_diff_route_import.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_direct_import.py' 'D:\Dev\kha\test_direct_import.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_direct_pipeline.py' 'D:\Dev\kha\test_direct_pipeline.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_direct_wrapper.py' 'D:\Dev\kha\test_direct_wrapper.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_dll_load.py' 'D:\Dev\kha\test_dll_load.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_endpoints_quick.py' 'D:\Dev\kha\test_endpoints_quick.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_entity_phase_bond.py' 'D:\Dev\kha\test_entity_phase_bond.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_entropy_complete.py' 'D:\Dev\kha\test_entropy_complete.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_entropy_direct.py' 'D:\Dev\kha\test_entropy_direct.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_entropy_final.py' 'D:\Dev\kha\test_entropy_final.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_entropy_pruning.py' 'D:\Dev\kha\test_entropy_pruning.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_entropy_state.py' 'D:\Dev\kha\test_entropy_state.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_entropy_with_averror.py' 'D:\Dev\kha\test_entropy_with_averror.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_entropy_with_spec.py' 'D:\Dev\kha\test_entropy_with_spec.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_exception_logging.py' 'D:\Dev\kha\test_exception_logging.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_extraction_direct.py' 'D:\Dev\kha\test_extraction_direct.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_fastapi.py' 'D:\Dev\kha\test_fastapi.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_fixed_scripts.py' 'D:\Dev\kha\test_fixed_scripts.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_fp16_speed.py' 'D:\Dev\kha\test_fp16_speed.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_frontend_diagnostic.py' 'D:\Dev\kha\test_frontend_diagnostic.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_full_api_import.py' 'D:\Dev\kha\test_full_api_import.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_full_pipeline.py' 'D:\Dev\kha\test_full_pipeline.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_gpu_speed.py' 'D:\Dev\kha\test_gpu_speed.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_graceful_shutdown.py' 'D:\Dev\kha\test_graceful_shutdown.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_health_endpoint.py' 'D:\Dev\kha\test_health_endpoint.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_imports.py' 'D:\Dev\kha\test_imports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_imports_fixed.py' 'D:\Dev\kha\test_imports_fixed.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_import_chain.py' 'D:\Dev\kha\test_import_chain.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_improved_pipeline.py' 'D:\Dev\kha\test_improved_pipeline.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_improvements.py' 'D:\Dev\kha\test_improvements.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_ingestion_pipeline.py' 'D:\Dev\kha\test_ingestion_pipeline.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_ingestion_simple.py' 'D:\Dev\kha\test_ingestion_simple.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_instruction_overhead.py' 'D:\Dev\kha\test_instruction_overhead.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_integration.py' 'D:\Dev\kha\test_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_json_fixes.py' 'D:\Dev\kha\test_json_fixes.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_manifest_fix.py' 'D:\Dev\kha\test_manifest_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_mesh_lockdown.py' 'D:\Dev\kha\test_mesh_lockdown.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_metacognitive_integration.py' 'D:\Dev\kha\test_metacognitive_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_minimal.py' 'D:\Dev\kha\test_minimal.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_minimal_speed.py' 'D:\Dev\kha\test_minimal_speed.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_multimodal_pipeline.py' 'D:\Dev\kha\test_multimodal_pipeline.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_multi_tenant_system.py' 'D:\Dev\kha\test_multi_tenant_system.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_natural_filtering.py' 'D:\Dev\kha\test_natural_filtering.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_netflix_destruction.py' 'D:\Dev\kha\test_netflix_destruction.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_nonetype_fix.py' 'D:\Dev\kha\test_nonetype_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_optimized_math.py' 'D:\Dev\kha\test_optimized_math.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_oscillator_import.py' 'D:\Dev\kha\test_oscillator_import.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_package.py' 'D:\Dev\kha\test_package.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_pcc_broadcast.py' 'D:\Dev\kha\test_pcc_broadcast.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_pdf_extraction.py' 'D:\Dev\kha\test_pdf_extraction.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_pdf_fix.py' 'D:\Dev\kha\test_pdf_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_pdf_pipeline.py' 'D:\Dev\kha\test_pdf_pipeline.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_pdf_upload.py' 'D:\Dev\kha\test_pdf_upload.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_penrose.py' 'D:\Dev\kha\test_penrose.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_penrose_cache.py' 'D:\Dev\kha\test_penrose_cache.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_penrose_direct.py' 'D:\Dev\kha\test_penrose_direct.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_penrose_engine.py' 'D:\Dev\kha\test_penrose_engine.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_penrose_forced.py' 'D:\Dev\kha\test_penrose_forced.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_penrose_production.py' 'D:\Dev\kha\test_penrose_production.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_penrose_standalone.py' 'D:\Dev\kha\test_penrose_standalone.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_persistence.py' 'D:\Dev\kha\test_persistence.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_phase7_direct.py' 'D:\Dev\kha\test_phase7_direct.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_phase_8_integration.py' 'D:\Dev\kha\test_phase_8_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_phase_encoding.py' 'D:\Dev\kha\test_phase_encoding.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_prajna_audio_visual.py' 'D:\Dev\kha\test_prajna_audio_visual.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_prajna_direct.py' 'D:\Dev\kha\test_prajna_direct.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_prajna_health.py' 'D:\Dev\kha\test_prajna_health.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_prajna_imports.py' 'D:\Dev\kha\test_prajna_imports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_prajna_integration.py' 'D:\Dev\kha\test_prajna_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_prajna_quick.py' 'D:\Dev\kha\test_prajna_quick.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_prajna_tonka_coordination.py' 'D:\Dev\kha\test_prajna_tonka_coordination.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_preflight.py' 'D:\Dev\kha\test_preflight.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_production_pipeline.py' 'D:\Dev\kha\test_production_pipeline.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_prosody_wiring.py' 'D:\Dev\kha\test_prosody_wiring.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_python_api.py' 'D:\Dev\kha\test_python_api.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_python_extraction.py' 'D:\Dev\kha\test_python_extraction.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_quantum_paper_filtering.py' 'D:\Dev\kha\test_quantum_paper_filtering.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_real_500_error.py' 'D:\Dev\kha\test_real_500_error.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_real_tori_filtering.py' 'D:\Dev\kha\test_real_tori_filtering.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_reasoning_traversal.py' 'D:\Dev\kha\test_reasoning_traversal.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_route_mounting.py' 'D:\Dev\kha\test_route_mounting.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_route_simple.py' 'D:\Dev\kha\test_route_simple.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_scholarsphere_integration.py' 'D:\Dev\kha\test_scholarsphere_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_scholarsphere_progress.py' 'D:\Dev\kha\test_scholarsphere_progress.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_scholarsphere_sync.py' 'D:\Dev\kha\test_scholarsphere_sync.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_self_transformation.py' 'D:\Dev\kha\test_self_transformation.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_semantic_pdf_ingestion.py' 'D:\Dev\kha\test_semantic_pdf_ingestion.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_serialization_fix.py' 'D:\Dev\kha\test_serialization_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_simple.py' 'D:\Dev\kha\test_simple.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_simple_embedding.py' 'D:\Dev\kha\test_simple_embedding.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_soliton.py' 'D:\Dev\kha\test_soliton.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_soliton_api.py' 'D:\Dev\kha\test_soliton_api.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_soliton_complete.py' 'D:\Dev\kha\test_soliton_complete.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_soliton_diagnostic.py' 'D:\Dev\kha\test_soliton_diagnostic.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_soliton_endpoints.py' 'D:\Dev\kha\test_soliton_endpoints.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_soliton_final.py' 'D:\Dev\kha\test_soliton_final.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_soliton_fix.py' 'D:\Dev\kha\test_soliton_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_soliton_import.py' 'D:\Dev\kha\test_soliton_import.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_soliton_pdf.py' 'D:\Dev\kha\test_soliton_pdf.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_spacetime_memory.py' 'D:\Dev\kha\test_spacetime_memory.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_telemetry.py' 'D:\Dev\kha\test_telemetry.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_temp.py' 'D:\Dev\kha\test_temp.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_tonka_integration.py' 'D:\Dev\kha\test_tonka_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_tori_8002.py' 'D:\Dev\kha\test_tori_8002.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_tori_standalone.py' 'D:\Dev\kha\test_tori_standalone.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_tori_system.py' 'D:\Dev\kha\test_tori_system.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_trace.py' 'D:\Dev\kha\test_trace.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_true_metacognition.py' 'D:\Dev\kha\test_true_metacognition.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_ultimate_nonetype_elimination.py' 'D:\Dev\kha\test_ultimate_nonetype_elimination.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_unified_ingestion.py' 'D:\Dev\kha\test_unified_ingestion.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_unified_mesh_parameterization.py' 'D:\Dev\kha\test_unified_mesh_parameterization.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_vllm_embeddings.py' 'D:\Dev\kha\test_vllm_embeddings.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_windows_timeout.py' 'D:\Dev\kha\test_windows_timeout.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_with_av_skip.py' 'D:\Dev\kha\test_with_av_skip.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_with_real_pdf.py' 'D:\Dev\kha\test_with_real_pdf.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_with_small_model.py' 'D:\Dev\kha\test_with_small_model.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_workaround.py' 'D:\Dev\kha\test_workaround.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\benchmarks\test_working_topologies.py' 'D:\Dev\kha\test_working_topologies.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\check_dependencies.py' 'D:\Dev\kha\check_dependencies.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\check_duplicate_endpoints.py' 'D:\Dev\kha\check_duplicate_endpoints.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\check_exports.py' 'D:\Dev\kha\check_exports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\check_merge_gate_status.py' 'D:\Dev\kha\check_merge_gate_status.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\check_ndarray_features.py' 'D:\Dev\kha\check_ndarray_features.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\check_pdf_dependencies.py' 'D:\Dev\kha\check_pdf_dependencies.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\check_penrose_gap.py' 'D:\Dev\kha\check_penrose_gap.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\check_prajna_status.py' 'D:\Dev\kha\check_prajna_status.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\check_sprint_status.py' 'D:\Dev\kha\check_sprint_status.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\check_tori_status.py' 'D:\Dev\kha\check_tori_status.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\check_trace_fixes.py' 'D:\Dev\kha\check_trace_fixes.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\debug_concept_mesh_import.py' 'D:\Dev\kha\debug_concept_mesh_import.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\debug_penrose.py' 'D:\Dev\kha\debug_penrose.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\debug_soliton_endpoints.py' 'D:\Dev\kha\debug_soliton_endpoints.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\debug_soliton_final.py' 'D:\Dev\kha\debug_soliton_final.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\debug_soliton_fixed.py' 'D:\Dev\kha\debug_soliton_fixed.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\debug_soliton_pdf.py' 'D:\Dev\kha\debug_soliton_pdf.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_and_fix_tori.py' 'D:\Dev\kha\diagnose_and_fix_tori.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_api_import.py' 'D:\Dev\kha\diagnose_api_import.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_av.py' 'D:\Dev\kha\diagnose_av.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_conceptmesh.py' 'D:\Dev\kha\diagnose_conceptmesh.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_conceptmesh_imports.py' 'D:\Dev\kha\diagnose_conceptmesh_imports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_concept_mesh.py' 'D:\Dev\kha\diagnose_concept_mesh.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_gpu_issue.py' 'D:\Dev\kha\diagnose_gpu_issue.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_issues.py' 'D:\Dev\kha\diagnose_issues.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_login.py' 'D:\Dev\kha\diagnose_login.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_mcp_service.py' 'D:\Dev\kha\diagnose_mcp_service.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_memory_unification.py' 'D:\Dev\kha\diagnose_memory_unification.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_penrose.py' 'D:\Dev\kha\diagnose_penrose.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_penrose_microkernel.py' 'D:\Dev\kha\diagnose_penrose_microkernel.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_slow_embeddings.py' 'D:\Dev\kha\diagnose_slow_embeddings.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_soliton.py' 'D:\Dev\kha\diagnose_soliton.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_soliton_500.py' 'D:\Dev\kha\diagnose_soliton_500.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_soliton_complete.py' 'D:\Dev\kha\diagnose_soliton_complete.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_soliton_init.py' 'D:\Dev\kha\diagnose_soliton_init.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_stats_format.py' 'D:\Dev\kha\diagnose_stats_format.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_torus_cells.py' 'D:\Dev\kha\diagnose_torus_cells.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnose_vite_imports.py' 'D:\Dev\kha\diagnose_vite_imports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnostic.py' 'D:\Dev\kha\diagnostic.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\diagnostic\diagnostic_bps_intent.py' 'D:\Dev\kha\diagnostic_bps_intent.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\emergency_analysis.ps1' 'D:\Dev\kha\emergency_analysis.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\emergency_dependency_fix.ps1' 'D:\Dev\kha\emergency_dependency_fix.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\emergency_fix.py' 'D:\Dev\kha\emergency_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\emergency_fix_v2.ps1' 'D:\Dev\kha\emergency_fix_v2.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\EMERGENCY_KILL_ALL_NODE.ps1' 'D:\Dev\kha\EMERGENCY_KILL_ALL_NODE.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\emergency_websockets_fix.py' 'D:\Dev\kha\emergency_websockets_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\NUCLEAR-FIX-NOW.ps1' 'D:\Dev\kha\NUCLEAR-FIX-NOW.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\nuclear_audit_and_fix.py' 'D:\Dev\kha\nuclear_audit_and_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\nuclear_clear.py' 'D:\Dev\kha\nuclear_clear.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\nuclear_fix_numpy_abi.ps1' 'D:\Dev\kha\nuclear_fix_numpy_abi.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\nuclear_simple_hologram.py' 'D:\Dev\kha\nuclear_simple_hologram.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_actual_53.cjs' 'D:\Dev\kha\fix_actual_53.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_all_78.cjs' 'D:\Dev\kha\fix_all_78.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_all_concept_mesh_issues.py' 'D:\Dev\kha\fix_all_concept_mesh_issues.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\FIX_ALL_CRITICAL_ISSUES.bat' 'D:\Dev\kha\FIX_ALL_CRITICAL_ISSUES.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_all_group_params.ps1' 'D:\Dev\kha\fix_all_group_params.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_all_safe.py' 'D:\Dev\kha\fix_all_safe.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_all_shaders.ps1' 'D:\Dev\kha\fix_all_shaders.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_all_tori_launch_errors.py' 'D:\Dev\kha\fix_all_tori_launch_errors.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_all_ts_errors.js' 'D:\Dev\kha\fix_all_ts_errors.js' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_all_ts_errors_complete.cjs' 'D:\Dev\kha\fix_all_ts_errors_complete.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_all_typescript_errors_final.cjs' 'D:\Dev\kha\fix_all_typescript_errors_final.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_all_typescript_issues.py' 'D:\Dev\kha\fix_all_typescript_issues.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_and_start.ps1' 'D:\Dev\kha\fix_and_start.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_api_health_timing.py' 'D:\Dev\kha\fix_api_health_timing.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_av_compat.bat' 'D:\Dev\kha\fix_av_compat.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_av_issue.py' 'D:\Dev\kha\fix_av_issue.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_blockers_simple.ps1' 'D:\Dev\kha\fix_blockers_simple.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_both_issues.py' 'D:\Dev\kha\fix_both_issues.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_both_issues_simple.py' 'D:\Dev\kha\fix_both_issues_simple.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_braces.py' 'D:\Dev\kha\fix_braces.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_brace_final.py' 'D:\Dev\kha\fix_brace_final.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_bridge_ports.py' 'D:\Dev\kha\fix_bridge_ports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_build_issues.cjs' 'D:\Dev\kha\fix_build_issues.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_cargo_toml_rust_backend.py' 'D:\Dev\kha\fix_cargo_toml_rust_backend.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_cascade.cjs' 'D:\Dev\kha\fix_cascade.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_complete.py' 'D:\Dev\kha\fix_complete.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_conceptdb_correct.py' 'D:\Dev\kha\fix_conceptdb_correct.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_conceptdb_error.py' 'D:\Dev\kha\fix_conceptdb_error.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_conceptmesh_focused.py' 'D:\Dev\kha\fix_conceptmesh_focused.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_conceptmesh_imports.py' 'D:\Dev\kha\fix_conceptmesh_imports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_conceptmesh_init.py' 'D:\Dev\kha\fix_conceptmesh_init.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_concept_db_critical.py' 'D:\Dev\kha\fix_concept_db_critical.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_concept_db_location.py' 'D:\Dev\kha\fix_concept_db_location.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_concept_extraction.py' 'D:\Dev\kha\fix_concept_extraction.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_concept_filenames.py' 'D:\Dev\kha\fix_concept_filenames.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_concept_files.py' 'D:\Dev\kha\fix_concept_files.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_concept_mesh_import.py' 'D:\Dev\kha\fix_concept_mesh_import.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_concept_mesh_imports.bat' 'D:\Dev\kha\fix_concept_mesh_imports.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_concept_mesh_imports.py' 'D:\Dev\kha\fix_concept_mesh_imports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_concept_mesh_imports_v2.bat' 'D:\Dev\kha\fix_concept_mesh_imports_v2.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_concept_mesh_loader.py' 'D:\Dev\kha\fix_concept_mesh_loader.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_concurrency_final.py' 'D:\Dev\kha\fix_concurrency_final.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\FIX_CRITICAL.bat' 'D:\Dev\kha\FIX_CRITICAL.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_critical_components.py' 'D:\Dev\kha\fix_critical_components.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_critical_concept_files.py' 'D:\Dev\kha\fix_critical_concept_files.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_critical_deps.bat' 'D:\Dev\kha\fix_critical_deps.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_critical_issues.py' 'D:\Dev\kha\fix_critical_issues.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_direct_syntax.cjs' 'D:\Dev\kha\fix_direct_syntax.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_document_extraction.bat' 'D:\Dev\kha\fix_document_extraction.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_duplicate_code.py' 'D:\Dev\kha\fix_duplicate_code.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_duplicate_endpoints.py' 'D:\Dev\kha\fix_duplicate_endpoints.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_duplicate_registrations.py' 'D:\Dev\kha\fix_duplicate_registrations.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_embed_function.py' 'D:\Dev\kha\fix_embed_function.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_empty_lattice.py' 'D:\Dev\kha\fix_empty_lattice.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_encoding.bat' 'D:\Dev\kha\fix_encoding.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_encoding_issues.py' 'D:\Dev\kha\fix_encoding_issues.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_entropy_import.py' 'D:\Dev\kha\fix_entropy_import.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_entropy_prune.bat' 'D:\Dev\kha\fix_entropy_prune.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_entropy_pruning.ps1' 'D:\Dev\kha\fix_entropy_pruning.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_exact_duplicate.py' 'D:\Dev\kha\fix_exact_duplicate.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_exact_syntax.cjs' 'D:\Dev\kha\fix_exact_syntax.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_fastmcp_duplicates.py' 'D:\Dev\kha\fix_fastmcp_duplicates.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_final_3_issues.ps1' 'D:\Dev\kha\fix_final_3_issues.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_final_48.cjs' 'D:\Dev\kha\fix_final_48.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_final_4_errors.cjs' 'D:\Dev\kha\fix_final_4_errors.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_final_54.cjs' 'D:\Dev\kha\fix_final_54.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_final_58.cjs' 'D:\Dev\kha\fix_final_58.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_final_6.cjs' 'D:\Dev\kha\fix_final_6.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_final_96.cjs' 'D:\Dev\kha\fix_final_96.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_final_shaders.ps1' 'D:\Dev\kha\fix_final_shaders.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_frontend_and_bridges.py' 'D:\Dev\kha\fix_frontend_and_bridges.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_frontend_dependencies.py' 'D:\Dev\kha\fix_frontend_dependencies.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_frontend_issues.py' 'D:\Dev\kha\fix_frontend_issues.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_frontend_typescript_remaining.py' 'D:\Dev\kha\fix_frontend_typescript_remaining.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_hologram_and_launcher_issues.py' 'D:\Dev\kha\fix_hologram_and_launcher_issues.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_hologram_autostart.py' 'D:\Dev\kha\fix_hologram_autostart.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_hologram_complete.py' 'D:\Dev\kha\fix_hologram_complete.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_hologram_startup.py' 'D:\Dev\kha\fix_hologram_startup.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_hologram_startup_complete.py' 'D:\Dev\kha\fix_hologram_startup_complete.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_holographic_display.py' 'D:\Dev\kha\fix_holographic_display.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_holographic_display_api.py' 'D:\Dev\kha\fix_holographic_display_api.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_holographic_enhanced.py' 'D:\Dev\kha\fix_holographic_enhanced.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_immediate_issues.py' 'D:\Dev\kha\fix_immediate_issues.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_imports_final.ps1' 'D:\Dev\kha\fix_imports_final.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_incomplete_hologram.py' 'D:\Dev\kha\fix_incomplete_hologram.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_intent_tracker.ps1' 'D:\Dev\kha\fix_intent_tracker.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_last_ts_errors.cjs' 'D:\Dev\kha\fix_last_ts_errors.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_lattice_oscillators.py' 'D:\Dev\kha\fix_lattice_oscillators.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_launcher_imports.py' 'D:\Dev\kha\fix_launcher_imports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_launcher_sequence.py' 'D:\Dev\kha\fix_launcher_sequence.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_main_propagation.ps1' 'D:\Dev\kha\fix_main_propagation.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_master_hub.cjs' 'D:\Dev\kha\fix_master_hub.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_mcp_complete.bat' 'D:\Dev\kha\fix_mcp_complete.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_mcp_dependencies.bat' 'D:\Dev\kha\fix_mcp_dependencies.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_mcp_duplicates.py' 'D:\Dev\kha\fix_mcp_duplicates.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_mcp_metacognitive.bat' 'D:\Dev\kha\fix_mcp_metacognitive.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_mcp_router_simple.py' 'D:\Dev\kha\fix_mcp_router_simple.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_mcp_router_warning.py' 'D:\Dev\kha\fix_mcp_router_warning.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_mcp_server_run.py' 'D:\Dev\kha\fix_mcp_server_run.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_mcp_simple.bat' 'D:\Dev\kha\fix_mcp_simple.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_mcp_transport.py' 'D:\Dev\kha\fix_mcp_transport.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_mcp_warning.py' 'D:\Dev\kha\fix_mcp_warning.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_mcp_warning_clean.py' 'D:\Dev\kha\fix_mcp_warning_clean.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_menu.py' 'D:\Dev\kha\fix_menu.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_mesh_warnings.ps1' 'D:\Dev\kha\fix_mesh_warnings.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_mesh_warnings_fixed.ps1' 'D:\Dev\kha\fix_mesh_warnings_fixed.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_npm_cleanup_warning.ps1' 'D:\Dev\kha\fix_npm_cleanup_warning.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_numpy_abi.ps1' 'D:\Dev\kha\fix_numpy_abi.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_numpy_abi_enhanced.ps1' 'D:\Dev\kha\fix_numpy_abi_enhanced.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_numpy_abi_original.ps1' 'D:\Dev\kha\fix_numpy_abi_original.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_numpy_bps_ready.py' 'D:\Dev\kha\fix_numpy_bps_ready.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_numpy_compatibility.ps1' 'D:\Dev\kha\fix_numpy_compatibility.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_ocr_libraries.bat' 'D:\Dev\kha\fix_ocr_libraries.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_openblas_and_build.py' 'D:\Dev\kha\fix_openblas_and_build.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_oscillator_lattice.bat' 'D:\Dev\kha\fix_oscillator_lattice.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_page_split.py' 'D:\Dev\kha\fix_page_split.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_penrose_mcp_complete.py' 'D:\Dev\kha\fix_penrose_mcp_complete.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_persistent.cjs' 'D:\Dev\kha\fix_persistent.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_phase_event_bus.py' 'D:\Dev\kha\fix_phase_event_bus.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_phase_event_bus_final.py' 'D:\Dev\kha\fix_phase_event_bus_final.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_photomorph_import.py' 'D:\Dev\kha\fix_photomorph_import.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_pipeline_issues.py' 'D:\Dev\kha\fix_pipeline_issues.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_poetry_scipy.ps1' 'D:\Dev\kha\fix_poetry_scipy.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_prajna_init_files.py' 'D:\Dev\kha\fix_prajna_init_files.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_prajna_syntax.py' 'D:\Dev\kha\fix_prajna_syntax.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_precise_brace.py' 'D:\Dev\kha\fix_precise_brace.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_profile.ps1' 'D:\Dev\kha\fix_profile.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_propagation_line_476.ps1' 'D:\Dev\kha\fix_propagation_line_476.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_propagation_placement.ps1' 'D:\Dev\kha\fix_propagation_placement.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_propagation_targeted.ps1' 'D:\Dev\kha\fix_propagation_targeted.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_pydantic_v2_complete.py' 'D:\Dev\kha\fix_pydantic_v2_complete.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_realghostengine_complete.py' 'D:\Dev\kha\fix_realghostengine_complete.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_realghostengine_imports.py' 'D:\Dev\kha\fix_realghostengine_imports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_remaining_ts_errors.cjs' 'D:\Dev\kha\fix_remaining_ts_errors.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_remove_ndarray_linalg.py' 'D:\Dev\kha\fix_remove_ndarray_linalg.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_rust_crate.py' 'D:\Dev\kha\fix_rust_crate.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_rust_modules.py' 'D:\Dev\kha\fix_rust_modules.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_scholarsphere_fallback.py' 'D:\Dev\kha\fix_scholarsphere_fallback.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_session_cache_types.cjs' 'D:\Dev\kha\fix_session_cache_types.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_shaders.ps1' 'D:\Dev\kha\fix_shaders.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_shaders_enhanced.ps1' 'D:\Dev\kha\fix_shaders_enhanced.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_soliton_aliases.py' 'D:\Dev\kha\fix_soliton_aliases.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_soliton_endpoints.py' 'D:\Dev\kha\fix_soliton_endpoints.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_soliton_imports.py' 'D:\Dev\kha\fix_soliton_imports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_soliton_init_route.py' 'D:\Dev\kha\fix_soliton_init_route.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_soliton_init_typo.py' 'D:\Dev\kha\fix_soliton_init_typo.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_soliton_integration.py' 'D:\Dev\kha\fix_soliton_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_soliton_memory.py' 'D:\Dev\kha\fix_soliton_memory.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_soliton_now.py' 'D:\Dev\kha\fix_soliton_now.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_soliton_routes.py' 'D:\Dev\kha\fix_soliton_routes.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_soliton_stats_error.py' 'D:\Dev\kha\fix_soliton_stats_error.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_startup_noise.py' 'D:\Dev\kha\fix_startup_noise.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_startup_timing.ps1' 'D:\Dev\kha\fix_startup_timing.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_startup_warnings.py' 'D:\Dev\kha\fix_startup_warnings.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_svelte_additional_7_10.py' 'D:\Dev\kha\fix_svelte_additional_7_10.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_svelte_comprehensive.cjs' 'D:\Dev\kha\fix_svelte_comprehensive.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_svelte_final.cjs' 'D:\Dev\kha\fix_svelte_final.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_svelte_round2.cjs' 'D:\Dev\kha\fix_svelte_round2.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_svelte_specific.cjs' 'D:\Dev\kha\fix_svelte_specific.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_svelte_systematic.cjs' 'D:\Dev\kha\fix_svelte_systematic.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_svelte_types.js' 'D:\Dev\kha\fix_svelte_types.js' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_svelte_typescript_complete.py' 'D:\Dev\kha\fix_svelte_typescript_complete.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_svelte_typescript_extended.py' 'D:\Dev\kha\fix_svelte_typescript_extended.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_syntax_error.py' 'D:\Dev\kha\fix_syntax_error.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_syntax_errors.cjs' 'D:\Dev\kha\fix_syntax_errors.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_syntax_minimal.py' 'D:\Dev\kha\fix_syntax_minimal.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_syntax_only.py' 'D:\Dev\kha\fix_syntax_only.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_system_components.py' 'D:\Dev\kha\fix_system_components.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_test_port.bat' 'D:\Dev\kha\fix_test_port.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_textureload_comprehensive.ps1' 'D:\Dev\kha\fix_textureload_comprehensive.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_texture_load_args.ps1' 'D:\Dev\kha\fix_texture_load_args.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_toggle_function.py' 'D:\Dev\kha\fix_toggle_function.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_tori_automatic.py' 'D:\Dev\kha\fix_tori_automatic.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_tori_automatic_v2.py' 'D:\Dev\kha\fix_tori_automatic_v2.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_tori_automatic_v3.py' 'D:\Dev\kha\fix_tori_automatic_v3.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_tori_blockers.ps1' 'D:\Dev\kha\fix_tori_blockers.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_tori_blockers_v2.ps1' 'D:\Dev\kha\fix_tori_blockers_v2.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_tori_issues.py' 'D:\Dev\kha\fix_tori_issues.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_tsconfig.py' 'D:\Dev\kha\fix_tsconfig.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_ts_errors.cjs' 'D:\Dev\kha\fix_ts_errors.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_ts_errors_precise.cjs' 'D:\Dev\kha\fix_ts_errors_precise.cjs' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_ts_errors_precise.js' 'D:\Dev\kha\fix_ts_errors_precise.js' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_typescript_complete.py' 'D:\Dev\kha\fix_typescript_complete.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_typescript_errors.py' 'D:\Dev\kha\fix_typescript_errors.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_types_shadowing.py' 'D:\Dev\kha\fix_types_shadowing.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_utf8_errors.py' 'D:\Dev\kha\fix_utf8_errors.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_velocity_detailed.ps1' 'D:\Dev\kha\fix_velocity_detailed.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_velocity_flow_vis.ps1' 'D:\Dev\kha\fix_velocity_flow_vis.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_virtual_list_package.py' 'D:\Dev\kha\fix_virtual_list_package.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_vite_imports.py' 'D:\Dev\kha\fix_vite_imports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\fixes\fix_vite_proxy.js' 'D:\Dev\kha\fix_vite_proxy.js' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\Install-PenroseDeps.ps1' 'D:\Dev\kha\Install-PenroseDeps.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\INSTALL_DEPS.bat' 'D:\Dev\kha\INSTALL_DEPS.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_editable.ps1' 'D:\Dev\kha\install_editable.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_entropy_dependencies.py' 'D:\Dev\kha\install_entropy_dependencies.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_entropy_deps.bat' 'D:\Dev\kha\install_entropy_deps.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_ffmpeg.ps1' 'D:\Dev\kha\install_ffmpeg.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_ffmpeg_simple.ps1' 'D:\Dev\kha\install_ffmpeg_simple.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_missing_deps.bat' 'D:\Dev\kha\install_missing_deps.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\INSTALL_PENROSE_DEPS.bat' 'D:\Dev\kha\INSTALL_PENROSE_DEPS.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_penrose_deps.py' 'D:\Dev\kha\install_penrose_deps.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\INSTALL_PENROSE_NUMBA.bat' 'D:\Dev\kha\INSTALL_PENROSE_NUMBA.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\INSTALL_PENROSE_NUMBA.ps1' 'D:\Dev\kha\INSTALL_PENROSE_NUMBA.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_phase6_deepdiff.bat' 'D:\Dev\kha\install_phase6_deepdiff.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\INSTALL_PHASE6_DEPS.bat' 'D:\Dev\kha\INSTALL_PHASE6_DEPS.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_real_mcp_packages.py' 'D:\Dev\kha\install_real_mcp_packages.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_sentence_transformers_direct.py' 'D:\Dev\kha\install_sentence_transformers_direct.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_spacy_medium.py' 'D:\Dev\kha\install_spacy_medium.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_spacy_model.bat' 'D:\Dev\kha\install_spacy_model.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_test_deps.bat' 'D:\Dev\kha\install_test_deps.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_toml_parser.bat' 'D:\Dev\kha\install_toml_parser.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\INSTALL_TORI_DEPS.bat' 'D:\Dev\kha\INSTALL_TORI_DEPS.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_webgpu_types.ps1' 'D:\Dev\kha\install_webgpu_types.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\install_scripts\install_websockets_fix.py' 'D:\Dev\kha\install_websockets_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\patches\apply_all_fixes.py' 'D:\Dev\kha\apply_all_fixes.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\patches\apply_beyond_patches.py' 'D:\Dev\kha\apply_beyond_patches.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\patches\apply_final_review_fixes.py' 'D:\Dev\kha\apply_final_review_fixes.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\patches\apply_soliton_fix.py' 'D:\Dev\kha\apply_soliton_fix.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\patches\bdg_integration_patches.py' 'D:\Dev\kha\bdg_integration_patches.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\patches\create_hologram_patches.py' 'D:\Dev\kha\create_hologram_patches.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\patches\enhanced_launcher_api_flag_patch.py' 'D:\Dev\kha\enhanced_launcher_api_flag_patch.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\patches\enhanced_launcher_patch.py' 'D:\Dev\kha\enhanced_launcher_patch.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\patches\patch_launcher_v5.py' 'D:\Dev\kha\patch_launcher_v5.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\patches\pipeline_before_2nd_patches.py' 'D:\Dev\kha\pipeline_before_2nd_patches.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\patches\quality_patch.py' 'D:\Dev\kha\quality_patch.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\patches\verify_patches.py' 'D:\Dev\kha\verify_patches.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_all_fixes.bat' 'D:\Dev\kha\run_all_fixes.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_all_fixes.py' 'D:\Dev\kha\run_all_fixes.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_all_fixes_v2.bat' 'D:\Dev\kha\run_all_fixes_v2.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_ALL_OPTIMIZATIONS_TEST.bat' 'D:\Dev\kha\RUN_ALL_OPTIMIZATIONS_TEST.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_bps_test.py' 'D:\Dev\kha\run_bps_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_CORRECTED_ANALYSIS.bat' 'D:\Dev\kha\RUN_CORRECTED_ANALYSIS.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_CORRECTED_TEST.bat' 'D:\Dev\kha\RUN_CORRECTED_TEST.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_DEBUG_ACCURACY.bat' 'D:\Dev\kha\RUN_DEBUG_ACCURACY.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_DEBUG_PENROSE.bat' 'D:\Dev\kha\RUN_DEBUG_PENROSE.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_DIAGNOSE_MICROKERNEL.bat' 'D:\Dev\kha\RUN_DIAGNOSE_MICROKERNEL.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_DIAGNOSE_PENROSE.bat' 'D:\Dev\kha\RUN_DIAGNOSE_PENROSE.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_diagnostic.bat' 'D:\Dev\kha\run_diagnostic.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_embedding_service.py' 'D:\Dev\kha\run_embedding_service.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_embedding_service_graceful.py' 'D:\Dev\kha\run_embedding_service_graceful.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_enhanced_launcher.bat' 'D:\Dev\kha\run_enhanced_launcher.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_fixed_test.bat' 'D:\Dev\kha\run_fixed_test.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_GREMLIN_FIX.ps1' 'D:\Dev\kha\RUN_GREMLIN_FIX.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_legendary_test.py' 'D:\Dev\kha\run_legendary_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_PRODUCTION_FIX.bat' 'D:\Dev\kha\RUN_PRODUCTION_FIX.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_PRODUCTION_FIX.ps1' 'D:\Dev\kha\RUN_PRODUCTION_FIX.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_QUICK_OMEGA_TEST.bat' 'D:\Dev\kha\RUN_QUICK_OMEGA_TEST.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_RECURSIVE_TEST.bat' 'D:\Dev\kha\RUN_RECURSIVE_TEST.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_ROBUST_OMEGA_TEST.bat' 'D:\Dev\kha\RUN_ROBUST_OMEGA_TEST.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_soft_dedupe.py' 'D:\Dev\kha\run_soft_dedupe.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_SOLITON_TEST.bat' 'D:\Dev\kha\RUN_SOLITON_TEST.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_stable_server.py' 'D:\Dev\kha\run_stable_server.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_STRASSEN_TEST.bat' 'D:\Dev\kha\RUN_STRASSEN_TEST.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_test.bat' 'D:\Dev\kha\run_test.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_test.ps1' 'D:\Dev\kha\run_test.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_test.py' 'D:\Dev\kha\run_test.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_tests.py' 'D:\Dev\kha\run_tests.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_test_8002.py' 'D:\Dev\kha\run_test_8002.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_THIS_FINAL_FIX.ps1' 'D:\Dev\kha\RUN_THIS_FINAL_FIX.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\RUN_THIS_NOW.bat' 'D:\Dev\kha\RUN_THIS_NOW.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_tori.ps1' 'D:\Dev\kha\run_tori.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_tori_fixes_windows.bat' 'D:\Dev\kha\run_tori_fixes_windows.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_tori_fixes_windows.ps1' 'D:\Dev\kha\run_tori_fixes_windows.ps1' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_vault_audit.py' 'D:\Dev\kha\run_vault_audit.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\run_scripts\run_verification.bat' 'D:\Dev\kha\run_verification.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\uncategorized\.mcp.json' 'D:\Dev\kha\.mcp.json' -Force
Move-Item 'D:\Dev\kha\_archive\2024\uncategorized\.mcp.json.backup2' 'D:\Dev\kha\.mcp.json.backup2' -Force
Move-Item 'D:\Dev\kha\_archive\2024\uncategorized\.mcp.json.bulletproof' 'D:\Dev\kha\.mcp.json.bulletproof' -Force
Move-Item 'D:\Dev\kha\_archive\2024\uncategorized\consciousness_system.log' 'D:\Dev\kha\consciousness_system.log' -Force
Move-Item 'D:\Dev\kha\_archive\2024\uncategorized\conversations.zip' 'D:\Dev\kha\conversations.zip' -Force
Move-Item 'D:\Dev\kha\_archive\2024\uncategorized\corrected_omega_analysis.png' 'D:\Dev\kha\corrected_omega_analysis.png' -Force
Move-Item 'D:\Dev\kha\_archive\2024\uncategorized\elfin.vsix' 'D:\Dev\kha\elfin.vsix' -Force
Move-Item 'D:\Dev\kha\_archive\2024\uncategorized\hybrid_threshold_analysis.png' 'D:\Dev\kha\hybrid_threshold_analysis.png' -Force
Move-Item 'D:\Dev\kha\_archive\2024\uncategorized\master_execution_20250613_182139.log' 'D:\Dev\kha\master_execution_20250613_182139.log' -Force
Move-Item 'D:\Dev\kha\_archive\2024\uncategorized\penrose_microkernel_scaling.png' 'D:\Dev\kha\penrose_microkernel_scaling.png' -Force
Move-Item 'D:\Dev\kha\_archive\2024\uncategorized\quick_omega_test.png' 'D:\Dev\kha\quick_omega_test.png' -Force
Move-Item 'D:\Dev\kha\_archive\2024\uncategorized\universal_extraction_debug_20250607_091544.log' 'D:\Dev\kha\universal_extraction_debug_20250607_091544.log' -Force
Move-Item 'D:\Dev\kha\_archive\2024\uncategorized\working_topologies_result.png' 'D:\Dev\kha\working_topologies_result.png' -Force
Move-Item 'D:\Dev\kha\_archive\docs\reports\COMPATIBILITY_REPORT_20250702.md' 'D:\Dev\kha\COMPATIBILITY_REPORT_20250702.md' -Force
Move-Item 'D:\Dev\kha\_archive\docs\reports\DEPLOYMENT_CHECKLIST.md' 'D:\Dev\kha\DEPLOYMENT_CHECKLIST.md' -Force
Move-Item 'D:\Dev\kha\_archive\docs\reports\FINAL_MERGE_GATE_CHECKLIST.md' 'D:\Dev\kha\FINAL_MERGE_GATE_CHECKLIST.md' -Force
Move-Item 'D:\Dev\kha\_archive\docs\reports\health_report_20250720.md' 'D:\Dev\kha\health_report_20250720.md' -Force
Move-Item 'D:\Dev\kha\_archive\docs\reports\INTEGRATION_STATUS_REPORT.md' 'D:\Dev\kha\INTEGRATION_STATUS_REPORT.md' -Force
Move-Item 'D:\Dev\kha\_archive\docs\reports\NODB_MIGRATION_FINAL_REPORT.md' 'D:\Dev\kha\NODB_MIGRATION_FINAL_REPORT.md' -Force
Move-Item 'D:\Dev\kha\_archive\docs\reports\PRODUCTION_CHECKLIST.md' 'D:\Dev\kha\PRODUCTION_CHECKLIST.md' -Force
Move-Item 'D:\Dev\kha\_archive\docs\reports\QA_CHECKLIST.md' 'D:\Dev\kha\QA_CHECKLIST.md' -Force
Move-Item 'D:\Dev\kha\_archive\docs\reports\refactor_checklist.md' 'D:\Dev\kha\refactor_checklist.md' -Force
Move-Item 'D:\Dev\kha\_archive\docs\reports\VERIFICATION_CHECKLIST.md' 'D:\Dev\kha\VERIFICATION_CHECKLIST.md' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\create_hologram_patches.py.bak' 'D:\Dev\kha\create_hologram_patches.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\create_hologram_patches.py.bak.bak' 'D:\Dev\kha\create_hologram_patches.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\diagnose_concept_mesh.py.bak' 'D:\Dev\kha\diagnose_concept_mesh.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\diagnose_concept_mesh.py.bak.bak' 'D:\Dev\kha\diagnose_concept_mesh.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\enhanced_launcher.py.backup' 'D:\Dev\kha\enhanced_launcher.py.backup' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\extraction_summary.json.bak' 'D:\Dev\kha\extraction_summary.json.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\extraction_summary.json.bak.bak' 'D:\Dev\kha\extraction_summary.json.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\fix_concept_mesh_import.py.bak' 'D:\Dev\kha\fix_concept_mesh_import.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\fix_concept_mesh_import.py.bak.bak' 'D:\Dev\kha\fix_concept_mesh_import.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\fix_mcp_transport.py.bak' 'D:\Dev\kha\fix_mcp_transport.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\fix_mcp_transport.py.bak.bak' 'D:\Dev\kha\fix_mcp_transport.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\fix_suggestions.txt.bak' 'D:\Dev\kha\fix_suggestions.txt.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\fix_suggestions.txt.bak.bak' 'D:\Dev\kha\fix_suggestions.txt.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\flush_cache.py.bak' 'D:\Dev\kha\flush_cache.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\flush_cache.py.bak.bak' 'D:\Dev\kha\flush_cache.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\ingest_pdfs_only_FIXED.py.bak' 'D:\Dev\kha\ingest_pdfs_only_FIXED.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\ingest_pdfs_only_FIXED.py.bak.bak' 'D:\Dev\kha\ingest_pdfs_only_FIXED.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\launch_holographic_system.py.bak' 'D:\Dev\kha\launch_holographic_system.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\launch_holographic_system.py.bak.bak' 'D:\Dev\kha\launch_holographic_system.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\precise_change_analyzer.py.bak' 'D:\Dev\kha\precise_change_analyzer.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\precise_change_analyzer.py.bak.bak' 'D:\Dev\kha\precise_change_analyzer.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\psi_trajectory.json.bak' 'D:\Dev\kha\psi_trajectory.json.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\psi_trajectory.json.bak.bak' 'D:\Dev\kha\psi_trajectory.json.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\pyproject.toml.pep621.backup' 'D:\Dev\kha\pyproject.toml.pep621.backup' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\quick_pdf_test.py.bak' 'D:\Dev\kha\quick_pdf_test.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\quick_pdf_test.py.bak.bak' 'D:\Dev\kha\quick_pdf_test.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\smart_mirror.py.bak' 'D:\Dev\kha\smart_mirror.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\smart_mirror.py.bak.bak' 'D:\Dev\kha\smart_mirror.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\test_fastapi.py.bak' 'D:\Dev\kha\test_fastapi.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\test_fastapi.py.bak.bak' 'D:\Dev\kha\test_fastapi.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\test_windows_timeout.py.bak' 'D:\Dev\kha\test_windows_timeout.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\test_windows_timeout.py.bak.bak' 'D:\Dev\kha\test_windows_timeout.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\ultimate_consciousness_launcher.py.bak' 'D:\Dev\kha\ultimate_consciousness_launcher.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\ultimate_consciousness_launcher.py.bak.bak' 'D:\Dev\kha\ultimate_consciousness_launcher.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\ultimate_consciousness_launcher_windows.py.bak' 'D:\Dev\kha\ultimate_consciousness_launcher_windows.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\ultimate_consciousness_launcher_windows.py.bak.bak' 'D:\Dev\kha\ultimate_consciousness_launcher_windows.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\verify_tori_ready.py.bak' 'D:\Dev\kha\verify_tori_ready.py.bak' -Force
Move-Item 'D:\Dev\kha\_cleanup\duplicates\verify_tori_ready.py.bak.bak' 'D:\Dev\kha\verify_tori_ready.py.bak.bak' -Force
Move-Item 'D:\Dev\kha\tools\demo\beyond_demo.py' 'D:\Dev\kha\beyond_demo.py' -Force
Move-Item 'D:\Dev\kha\tools\demo\demo_clean_pipeline.py' 'D:\Dev\kha\demo_clean_pipeline.py' -Force
Move-Item 'D:\Dev\kha\tools\demo\demo_complete_system.py' 'D:\Dev\kha\demo_complete_system.py' -Force
Move-Item 'D:\Dev\kha\tools\demo\demo_enhanced_pipeline.py' 'D:\Dev\kha\demo_enhanced_pipeline.py' -Force
Move-Item 'D:\Dev\kha\tools\demo\demo_self_transformation.py' 'D:\Dev\kha\demo_self_transformation.py' -Force
Move-Item 'D:\Dev\kha\tools\demo\demo_universal_extraction.py' 'D:\Dev\kha\demo_universal_extraction.py' -Force
Move-Item 'D:\Dev\kha\tools\demo\temporal_knowledge_demo.py' 'D:\Dev\kha\temporal_knowledge_demo.py' -Force
Move-Item 'D:\Dev\kha\tools\demo\ultimate_demo.py' 'D:\Dev\kha\ultimate_demo.py' -Force

Write-Host 'Successfully restored 562 files!' -ForegroundColor Green
