# UNDO-HITLIST.ps1 - Generated 08/19/2025 14:15:49
Write-Host 'Restoring 49 files...' -ForegroundColor YellowMove-Item 'D:\Dev\kha\_archive\2024\backup\copy_concepts_correct_names.py' 'D:\Dev\kha\copy_concepts_correct_names.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\backup\pipeline_original_backup.py' 'D:\Dev\kha\pipeline_original_backup.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\build_setup\create_av_workaround.py' 'D:\Dev\kha\create_av_workaround.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\build_setup\create_av_workaround_fixed.py' 'D:\Dev\kha\create_av_workaround_fixed.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\build_setup\create_dev_install.bat' 'D:\Dev\kha\create_dev_install.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\build_setup\create_fixed_holographic_display.py' 'D:\Dev\kha\create_fixed_holographic_display.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\build_setup\create_ghost_zip.py' 'D:\Dev\kha\create_ghost_zip.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\build_setup\create_init_files.py' 'D:\Dev\kha\create_init_files.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\build_setup\create_missing_stubs.py' 'D:\Dev\kha\create_missing_stubs.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\build_setup\create_working_engine.py' 'D:\Dev\kha\create_working_engine.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\build_setup\init_concept_mesh_data.py' 'D:\Dev\kha\init_concept_mesh_data.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\build_setup\init_concept_mesh_data_canonical.py' 'D:\Dev\kha\init_concept_mesh_data_canonical.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\build_setup\init_concept_mesh_data_simple.py' 'D:\Dev\kha\init_concept_mesh_data_simple.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\cleanup\cleanup_ports.py' 'D:\Dev\kha\cleanup_ports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\cleanup\flush_cache.py' 'D:\Dev\kha\flush_cache.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\cleanup\kill_ports.py' 'D:\Dev\kha\kill_ports.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\cleanup\remove_duplicate_endpoints.py' 'D:\Dev\kha\remove_duplicate_endpoints.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\cleanup\remove_duplicate_soliton.py' 'D:\Dev\kha\remove_duplicate_soliton.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\force_benchmark_all.py' 'D:\Dev\kha\force_benchmark_all.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\emergency\force_shutdown_tori.py' 'D:\Dev\kha\force_shutdown_tori.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\migration\migrate_concepts.py' 'D:\Dev\kha\migrate_concepts.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\migration\migrate_to_metacognitive.py' 'D:\Dev\kha\migrate_to_metacognitive.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\migration\update_concept_mesh_references.py' 'D:\Dev\kha\update_concept_mesh_references.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\migration\update_numpy_pin.py' 'D:\Dev\kha\update_numpy_pin.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\migration\update_port.py' 'D:\Dev\kha\update_port.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\migration\update_prajna_audio_visual.py' 'D:\Dev\kha\update_prajna_audio_visual.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\migration\update_prosody_init.py' 'D:\Dev\kha\update_prosody_init.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\migration\update_readme_badge.py' 'D:\Dev\kha\update_readme_badge.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\migration\update_scholarsphere_integration.py' 'D:\Dev\kha\update_scholarsphere_integration.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\temp_files\temp_manager.py' 'D:\Dev\kha\temp_manager.py' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_api_startup.bat' 'D:\Dev\kha\test_api_startup.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_authenticated_upload.bat' 'D:\Dev\kha\test_authenticated_upload.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_complete.bat' 'D:\Dev\kha\test_complete.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_entropy_now.bat' 'D:\Dev\kha\test_entropy_now.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_final.bat' 'D:\Dev\kha\test_final.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_final_fix.bat' 'D:\Dev\kha\test_final_fix.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_frontend_direct.bat' 'D:\Dev\kha\test_frontend_direct.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\TEST_HOLOGRAPHIC_FIXES.bat' 'D:\Dev\kha\TEST_HOLOGRAPHIC_FIXES.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_import.bat' 'D:\Dev\kha\test_import.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_mcp_direct.bat' 'D:\Dev\kha\test_mcp_direct.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_mesh_lattice.bat' 'D:\Dev\kha\test_mesh_lattice.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\TEST_MULTI_TENANT_INTEGRATION.bat' 'D:\Dev\kha\TEST_MULTI_TENANT_INTEGRATION.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_phase6.bat' 'D:\Dev\kha\test_phase6.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_phase_6_8.bat' 'D:\Dev\kha\test_phase_6_8.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_proper_auth.bat' 'D:\Dev\kha\test_proper_auth.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_prosody.bat' 'D:\Dev\kha\test_prosody.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_singleton.bat' 'D:\Dev\kha\test_singleton.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\test_soliton.bat' 'D:\Dev\kha\test_soliton.bat' -Force
Move-Item 'D:\Dev\kha\_archive\2024\test_files\TEST_WORKING_TOPOLOGIES.bat' 'D:\Dev\kha\TEST_WORKING_TOPOLOGIES.bat' -Force
Write-Host 'Restored 49 files!' -ForegroundColor Green
