version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S'
  
  detailed:
    format: '%(asctime)s.%(msecs)03dZ | %(levelname)s | %(name)s | %(funcName)s | %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  adapter_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/inference/adapter_swap.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  mesh_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/mesh/export.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8
  
  phase_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/inference/phase_to_depth.log
    maxBytes: 5242880  # 5MB
    backupCount: 3
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

loggers:
  adapter_loader:
    level: DEBUG
    handlers: [adapter_file, console]
    propagate: false
  
  mesh_exporter:
    level: DEBUG
    handlers: [mesh_file, console]
    propagate: false
  
  phase_to_depth:
    level: DEBUG
    handlers: [phase_file, console]
    propagate: false
  
  tori:
    level: INFO
    handlers: [console, error_file]
    propagate: true

root:
  level: INFO
  handlers: [console, error_file]
