[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "concept_mesh"
version = "0.1.0"
description = "Concept mesh module"
authors = [{name = "Your Name"}]
dependencies = []
