[package]
name        = "{{name}}"
version     = "0.1.0"
authors     = ["{{author}}"]
edition     = "{{edition}}"
description = "Mobile robot navigation and control package using ELFIN"

[dependencies]
elfin-core  = "^1.0.0"
cvxpy       = "^1.4.0"
numpy       = "^1.20.0"
scipy       = "^1.7.0"
matplotlib  = "^3.5.0"
networkx    = "^2.6.0"   # For graph-based path planning

[solver]
mosek.enabled = true
mosek.msk_license_file = "${HOME}/mosek.lic"

[validation]
collision_checking.enabled = true
velocity_limits.enabled = true

[navigation]
default_planner = "rrt_star"
path_smoothing.enabled = true
dynamic_obstacles.enabled = true
