[package]
name = "penrose_engine_rs"
version = "0.1.1"
edition = "2021"

[lib]
name = "penrose_engine_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3  = { version = "0.21", features = ["extension-module"] }
ndarray = "0.15"
rayon  = "1.8"
